2022-09-19 08:53:09,614 : INFO : root : Loading config.
2022-09-19 08:53:09,617 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2022-09-19 08:53:09,618 : INFO : ConfigProcessor : Loading config from file C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\mpfconfig.yaml.
2022-09-19 08:53:09,683 : INFO : ConfigProcessor : Loading config: C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\mpfconfig.yaml
2022-09-19 08:53:09,683 : INFO : ConfigProcessor : Loading config from file C:\pinball\Pinball-MPF\ledtest\config\config.yaml.
2022-09-19 08:53:09,688 : INFO : ConfigProcessor : Loading config: C:\pinball\Pinball-MPF\ledtest\config\config.yaml
2022-09-19 08:53:09,689 : INFO : ConfigProcessor : Config file cache created: C:\Users\dorus\AppData\Local\Temp\2633cffb44c174c9692d362483fbe0d1.mpf_cache
2022-09-19 08:53:09,810 : INFO : ConfigProcessor : Loading config from file C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\modes\attract\config\attract.yaml.
2022-09-19 08:53:09,822 : INFO : ConfigProcessor : Loading config: C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\modes\attract\config\attract.yaml
2022-09-19 08:53:09,823 : INFO : ConfigProcessor : Config file cache created: C:\Users\dorus\AppData\Local\Temp\1bc14cc6bad4acaf01c10f8ebce93ea0.mpf_cache
2022-09-19 08:53:09,824 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\336e6d2601ccb63523c70814805acbf1.mpf_cache
2022-09-19 08:53:09,835 : INFO : Machine : Mission Pinball Framework Core Engine v0.55.0
2022-09-19 08:53:09,835 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2022-09-19-08-53-09-mpf-LAPTOP-AS8QDAQG.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2022-09-19 08:53:09,835 : INFO : Machine : MPF path: C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf
2022-09-19 08:53:09,835 : INFO : Machine : Machine path: C:\pinball\Pinball-MPF\ledtest
2022-09-19 08:53:09,835 : INFO : Machine : Platform: win32
2022-09-19 08:53:09,835 : INFO : Machine : Python executable location: C:\Users\dorus\AppData\Local\Programs\Python\Python38\python.exe
2022-09-19 08:53:09,836 : INFO : Machine : Python version: 3.8.10 (64-bit)
2022-09-19 08:53:09,838 : INFO : Machine : Initialise MPF.
2022-09-19 08:53:10,197 : INFO : OPP : Connecting to COM10 at 115200bps
2022-09-19 08:53:10,310 : INFO : OPP : Init of OPP board 0 done
2022-09-19 08:53:10,310 : INFO : OPP : Connecting to COM11 at 115200bps
2022-09-19 08:53:10,419 : INFO : OPP : Init of OPP board 1 done
2022-09-19 08:53:10,420 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2022-09-19 08:53:10,493 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2022-09-19 08:53:10,493 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.55.0', 'prev_value': None, 'change': True}
2022-09-19 08:53:10,493 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.55.0, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2022-09-19 08:53:10,493 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.8.10', 'prev_value': None, 'change': True}
2022-09-19 08:53:10,503 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19044-SP0', 'prev_value': None, 'change': True}
2022-09-19 08:53:10,503 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2022-09-19 08:53:10,503 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2022-09-19 08:53:10,503 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19044', 'prev_value': None, 'change': True}
2022-09-19 08:53:10,503 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2022-09-19 08:53:10,503 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2022-09-19 08:53:10,519 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2022-09-19 08:53:10,521 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2022-09-19 08:53:10,523 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2022-09-19 08:53:16,724 : INFO : BCPClientSocket : Connected BCP to 'local_display' localhost:5050
2022-09-19 08:53:16,725 : INFO : EventManager : Event: ======'bcp_clients_connected'====== Args={}
2022-09-19 08:53:16,843 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2022-09-19 08:53:16,850 : INFO : EventManager : Event: ======'init_phase_4'====== Args={}
2022-09-19 08:53:16,850 : INFO : EventManager : Event: ======'machine_var_mc_version'====== Args={'value': 'MPF-MC v0.55.0', 'prev_value': None, 'change': True}
2022-09-19 08:53:16,851 : INFO : EventManager : Event: ======'machine_var_mc_extended_version'====== Args={'value': 'MPF-MC v0.55.0 (config_version=5, BCP v1.1, Requires MPF v0.55.0-dev.49)', 'prev_value': None, 'change': True}
2022-09-19 08:53:16,863 : INFO : EventManager : Event: ======'machine_var_audits_events_game_started'====== Args={'value': 0, 'prev_value': None, 'change': True}
2022-09-19 08:53:16,864 : INFO : EventManager : Event: ======'machine_var_audits_events_game_ended'====== Args={'value': 0, 'prev_value': None, 'change': True}
2022-09-19 08:53:16,864 : INFO : EventManager : Event: ======'machine_var_audits_player_score'====== Args={'value': {'top': [], 'average': 0, 'total': 0}, 'prev_value': None, 'change': True}
2022-09-19 08:53:16,866 : INFO : EventManager : Event: ======'init_phase_5'====== Args={}
2022-09-19 08:53:16,871 : INFO : EventManager : Event: ======'init_done'====== Args={}
2022-09-19 08:53:16,872 : INFO : EventManager : Event: ======'machine_reset_phase_1'====== Args={}
2022-09-19 08:53:16,878 : INFO : EventManager : Event: ======'machine_reset_phase_2'====== Args={}
2022-09-19 08:53:16,879 : INFO : EventManager : Event: ======'machine_reset_phase_3'====== Args={}
2022-09-19 08:53:16,879 : INFO : EventManager : Event: ======'reset_complete'====== Args={}
2022-09-19 08:53:16,880 : INFO : EventManager : Event: ======'mode_attract_will_start'====== Args={}
2022-09-19 08:53:16,880 : INFO : EventManager : Event: ======'mode_attract_starting'====== Args={}
2022-09-19 08:53:16,880 : INFO : Mode.attract : Started. Priority: 10
2022-09-19 08:53:16,880 : INFO : EventManager : Event: ======'modes_active_modes_changed'====== Args={}
2022-09-19 08:53:16,880 : INFO : EventManager : Event: ======'mode_attract_started'====== Args={}
2022-09-19 08:53:16,881 : INFO : EventManager : Event: ======'collecting_balls_complete'====== Args={}
2022-09-19 08:53:16,894 : INFO : Machine : Starting the main run loop.
2022-09-19 08:53:30,731 : ERROR : asyncio : Exception in callback SerialTransport._poll_read()
handle: <TimerHandle when=246093.3905 SerialTransport._poll_read()>
Traceback (most recent call last):
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\serial_asyncio\__init__.py", line 275, in _poll_read
    if self.serial.in_waiting:
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'The device does not recognize the command.', None, 22))
2022-09-19 08:53:30,760 : INFO : Machine : Shutting down...
2022-09-19 08:53:30,763 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2022-09-19 08:53:30,764 : ERROR : OPP : Stop called on serial connection COM10
2022-09-19 08:53:30,765 : ERROR : OPP : Stop called on serial connection COM11
2022-09-19 08:53:30,766 : ERROR : asyncio : Exception in callback SerialTransport._call_connection_lost(None)
handle: <Handle SerialTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\serial_asyncio\__init__.py", line 390, in _call_connection_lost
    self._serial.flush()
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\serial\serialwin32.py", line 345, in flush
    while self.out_waiting:
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\serial\serialwin32.py", line 447, in out_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'The device does not recognize the command.', None, 22))
2022-09-19 08:53:30,767 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished name='Task-26' coro=<OppHardwarePlatform._poll_sender() done, defined at C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\platforms\opp\opp.py:918> exception=AttributeError("'NoneType' object has no attribute 'write'")>
Traceback (most recent call last):
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\platforms\opp\opp.py", line 934, in _poll_sender
    self.send_to_processor(chain_serial, self.read_input_msg[chain_serial])
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\platforms\opp\opp.py", line 315, in send_to_processor
    self.opp_connection[chain_serial].send(msg)
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\platforms\base_serial_communicator.py", line 155, in send
    self.writer.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
2022-09-19 08:53:30,791 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\core\machine.py", line 769, in _run_loop
    raise self._exception['exception']
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\serial_asyncio\__init__.py", line 275, in _poll_read
    if self.serial.in_waiting:
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'The device does not recognize the command.', None, 22))
2022-09-19 08:53:30,992 : ERROR : asyncio : Task was destroyed but it is pending!
task: <Task pending name='Task-25' coro=<OppHardwarePlatform._poll_sender() running at C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\platforms\opp\opp.py:928> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000002160AFA15B0>()]> cb=[Util.raise_exceptions() at C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\core\utility_functions.py:752]>
2022-09-19 08:53:30,993 : ERROR : asyncio : Task was destroyed but it is pending!
task: <Task pending name='Task-4157' coro=<Event.wait() running at C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\asyncio\locks.py:309> wait_for=<Future cancelled>>
2022-09-19 08:53:31,008 : ERROR : root : ClearCommError failed (PermissionError(13, 'The device does not recognize the command.', None, 22))
2022-09-19 08:53:31,010 : INFO : crash_reporter : Will not report crash as "report_crashes" mode is "never"
2022-09-19 08:53:31,010 : INFO : root : MPF run loop ended.
