2022-09-24 15:53:26,158 : INFO : root : Loading config.
2022-09-24 15:53:26,161 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2022-09-24 15:53:26,161 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\e58a4b50dd07e9e66a1a779c252c0c34.mpf_cache
2022-09-24 15:53:26,247 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\444cf03b543d197e203cfa23af3f8fc0.mpf_cache
2022-09-24 15:53:26,247 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\336e6d2601ccb63523c70814805acbf1.mpf_cache
2022-09-24 15:53:26,248 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\997bf01789d16ed996f231036966dd64.mpf_cache
2022-09-24 15:53:26,249 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\99703a5eb7b45595525b767565d37410.mpf_cache
2022-09-24 15:53:26,249 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\3bda3283678547d211760e16eb23b4da.mpf_cache
2022-09-24 15:53:26,250 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\9bc560b11d83fb4ed736b388b885a5d3.mpf_cache
2022-09-24 15:53:26,250 : INFO : Machine : Mission Pinball Framework Core Engine v0.55.0
2022-09-24 15:53:26,250 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2022-09-24-15-53-26-mpf-LAPTOP-AS8QDAQG.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2022-09-24 15:53:26,251 : INFO : Machine : MPF path: C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf
2022-09-24 15:53:26,251 : INFO : Machine : Machine path: C:\pinball\Pinball-MPF\mpfv1
2022-09-24 15:53:26,251 : INFO : Machine : Platform: win32
2022-09-24 15:53:26,251 : INFO : Machine : Python executable location: C:\Users\dorus\AppData\Local\Programs\Python\Python38\python.exe
2022-09-24 15:53:26,251 : INFO : Machine : Python version: 3.8.10 (64-bit)
2022-09-24 15:53:26,252 : INFO : Machine : Initialise MPF.
2022-09-24 15:53:26,406 : INFO : OPP : Connecting to COM10 at 115200bps
2022-09-24 15:53:26,407 : INFO : Machine : Shutting down...
2022-09-24 15:53:26,408 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2022-09-24 15:53:26,408 : ERROR : Machine : Failed to initialise MPF
Traceback (most recent call last):
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\core\machine.py", line 673, in initialise_mpf
    raise init.exception()
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\core\machine.py", line 244, in initialise
    await self.initialise_core_and_hardware()
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\core\machine.py", line 240, in initialise_core_and_hardware
    await self._initialize_platforms()
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\core\machine.py", line 331, in _initialize_platforms
    result.result()
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\platforms\opp\opp.py", line 105, in initialize
    await self._connect_to_hardware()
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\platforms\opp\opp.py", line 278, in _connect_to_hardware
    await comm.connect()
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\platforms\base_serial_communicator.py", line 45, in connect
    await self._connect_to_hardware(self.port, self.baud, self.xonxoff)
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\platforms\base_serial_communicator.py", line 54, in _connect_to_hardware
    self.reader, self.writer = await connector
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\core\clock.py", line 152, in open_serial_connection
    transport, _ = await create_serial_connection(
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\asyncio\coroutines.py", line 124, in coro
    res = func(*args, **kw)
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\serial_asyncio\__init__.py", line 410, in create_serial_connection
    ser = serial.serial_for_url(*args, **kwargs)
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\serial\__init__.py", line 90, in serial_for_url
    instance.open()
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM10': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2022-09-24 15:53:26,594 : INFO : crash_reporter : Will not report crash as "report_crashes" mode is "never"
2022-09-24 15:53:26,594 : INFO : root : MPF run loop ended.
