2019-07-13 14:51:36,935 : INFO : Machine : Mission Pinball Framework Core Engine v0.50.13
2019-07-13 14:51:36,936 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\dorus\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'logfile': 'logs\\2019-07-13-14-51-36-mpf-DESKTOP-6R98KNV.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None}
2019-07-13 14:51:36,936 : INFO : Machine : MPF path: c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpf
2019-07-13 14:51:36,936 : INFO : Machine : Machine path: C:\OPP\MPF\MPFTest
2019-07-13 14:51:36,936 : INFO : Machine : Platform: win32
2019-07-13 14:51:36,936 : INFO : Machine : Python executable location: c:\users\dorus\appdata\local\programs\python\python36\python.exe
2019-07-13 14:51:36,936 : INFO : Machine : Python version: 3.6.4 (64-bit)
2019-07-13 14:51:37,558 : INFO : Machine : Machine config file #1: config.yaml
2019-07-13 14:51:37,559 : WARNING : ConfigProcessor : Cache file not found: C:\Users\Dorus\AppData\Local\Temp\3e5a209b1cbf3ec3091eb81f26f5cfaa.mpf_cache
2019-07-13 14:51:37,559 : INFO : ConfigProcessor : Loading config from file c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml.
2019-07-13 14:51:37,693 : INFO : ConfigProcessor : Loading config: c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml
2019-07-13 14:51:37,695 : INFO : ConfigProcessor : Loading config from file C:\OPP\MPF\MPFTest\config\config.yaml.
2019-07-13 14:51:37,876 : ERROR : root : Error found in file C:\OPP\MPF\MPFTest\config\config.yaml: Version mismatch. Expected: #config_version=5 Actual: #config_version=3 Files: C:\OPP\MPF\MPFTest\config\config.yaml
Traceback (most recent call last):
  File "c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 193, in load
    expected_version_str, version_str, filename))
AssertionError: Version mismatch. Expected: #config_version=5 Actual: #config_version=3 Files: C:\OPP\MPF\MPFTest\config\config.yaml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpf\commands\game.py", line 208, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 158, in __init__
    self._load_config()
  File "c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 427, in _load_config
    store_to_cache=self.options['create_config_cache'])
  File "c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 111, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 131, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 154, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 208, in load
    raise ValueError(msg)
ValueError: Error found in file C:\OPP\MPF\MPFTest\config\config.yaml: Version mismatch. Expected: #config_version=5 Actual: #config_version=3 Files: C:\OPP\MPF\MPFTest\config\config.yaml
